version: '2'
services:
 consul:
  build: ./consul
  restart: always
  ports:
  - 8500:8500
  volumes:
  - consul_nginx_consul:/consul/data

 nginx:
  build: ./nginx
  restart: always
  ports:
  - 8580:80
  volumes:
  - consul_nginx_nginx:/usr/share/nginx/html
  - consul_nginx_consul-template:/consul-template

volumes:
 consul_nginx_consul:
 consul_nginx_nginx:
 consul_nginx_consul-template:
